services:
    abstractionary-server:
        build:
            context: .
        volumes:
            - ./history:/app/history
            - ./py_app/web:/app/web
            - ./py_app/static:/app/static
        ports:
            - 5001:5001
